name: AML Mod Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository...
      uses: actions/checkout@v3

    - name: Download AndroidModLoader`s mod template...
      uses: wei/wget@v1
      with:
        args: -O ./AML_src.zip https://github.com/RusJJ/AndroidModLoader/archive/refs/heads/main.zip

    - name: Install AndroidModLoader`s mod template...
      run: |
        unzip ./AML_src.zip
        mv ./AndroidModLoader-main/mod ./mod

    - name: Get SAUtils...
      uses: wei/wget@v1
      with:
        args: -O ./isautils.h https://github.com/AndroidModLoader/SAUtils/raw/main/isautils.h
        
    - name: Get GTA:SA structures file (private)...
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SSH }}
        SSH_HOSTKEYS: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_HOSTKEYS" > ~/.ssh/knowh_hosts
        eval `ssh-agent -s`
        echo "$SSH_KEY" > key
        chmod 600 key
        ssh-add key
        git clone ssh://git@ssh.github.com:443/RusJJ/GTASAAndroid_Structs.git ./structs
        mv ./structs/* ./

    - name: Install Android NDK (r24)...
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r24
        local-cache: true

    - name: Build the code...
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

    - name: Upload the mod!
      uses: actions/upload-artifact@v3
      with:
        name: compiled-mod.zip
        path: ./libs
